# Generated by Django 3.1.1 on 2020-09-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamista',
            fields=[
                ('ci', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tasa', models.FloatField()),
                ('interes', models.PositiveIntegerField()),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.prestamista')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('numeroCuota', models.PositiveIntegerField(db_column='numeroCuota', primary_key=True, serialize=False)),
                ('fechaVencimiento', models.DateTimeField()),
                ('fechaPago', models.DateTimeField()),
                ('valor', models.PositiveIntegerField()),
                ('identificador', models.ForeignKey(db_column='identificador', on_delete=django.db.models.deletion.PROTECT, to='main.prestamos')),
            ],
            options={
                'unique_together': {('identificador', 'numeroCuota')},
            },
        ),
    ]
