# Generated by Django 3.1.1 on 2020-09-18 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamista',
            name='address',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamista',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamista',
            name='last_name',
            field=models.TextField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamista',
            name='name',
            field=models.TextField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamista',
            name='phone',
            field=models.TextField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
