# Generated by Django 3.1.1 on 2020-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200918_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='cant_cuotas',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
    ]
